version: "3"
services:
  db:
    container_name: "postgres"
    image: postgres:10.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="mysecretpassword"
    networks:
      - backend

  users:
    container_name: "users"
    image: users-service:v1
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
    ports:
      - 5000:8000
    networks:
      - backend
    links:
      - db
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data:
