apiVersion: v1
kind: Service
metadata:
  name: users-postgres
  labels:
    app: users
spec:
  ports:
  - name: "postgres"
    port: 5432
  selector:
    app: users
    tier: postgres
  clusterIP: None
