apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: users
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: users
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50